Update gitee.py
Similar issue:
json.decoder.JSONDecodeError: Unterminated string starting at: line ** column xxxx (char xxx)
triggerred by:
__fetch_pull_requests ---- pulls = json.loads(raw_pulls) 
__get_pull_review_comments --- for comment in json.loads(raw_comments):

per_page change to 50 or 80, to solve first trigger point as a work a round. 
Because I thought it would be caused by big json files and parse error. 
So I cut down the size. 
we should find some other better solution next time, reference like https://stackoverflow.com/questions/49284203/python-json-loads-unterminated-string-error